# Generated by Django 2.2.1 on 2019-06-01 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

       # ('auth', '0011_update_proxy_permissions'),

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lifetime_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, max_length=30, null=True)),
                ('phone', models.TextField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('user_type', models.CharField(choices=[('N', 'Normal'), ('B', 'Broker'), ('A', 'Admin')], default='N', max_length=2)),
                ('cart', models.ManyToManyField(blank=True, related_name='cart', to='stocks.CartItem')),
                ('managed_users', models.ManyToManyField(blank=True, related_name='managed', to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(blank=True, to='dashboard.Order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
