# Generated by Django 2.2.1 on 2019-06-04 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='broker',
        ),
    ]
