# Generated by Django 2.2.1 on 2019-06-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokergroup',
            old_name='brokerName',
            new_name='brokerObj',
        ),
    ]
