# Generated by Django 2.2.1 on 2019-06-04 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_auto_20190531_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrokerGroup',
        ),
    ]
