# Generated by Django 2.2.1 on 2019-06-01 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('companyName', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100, null=True)),
                ('industry', models.CharField(max_length=100, null=True)),
                ('employees', models.IntegerField(null=True)),
                ('homePage', models.URLField(blank=True, max_length=512)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('exchange', models.CharField(choices=[('NY', 'NYSE'), ('NDQ', 'NASDAQ')], default='NDQ', max_length=10)),
                ('manager_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('stock_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='stock_detail', serialize=False, to='stocks.Company')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('openBid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('closeBid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.IntegerField()),
                ('dayRange', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.Company')),
            ],
        ),
    ]
